# Generated by Django 4.0.5 on 2022-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stock',
            field=models.ManyToManyField(blank=True, to='stocks_app.stock'),
        ),
    ]
